export const FETCH_TODOS_REQUESTED = 'FETCH_TODOS_REQUESTED'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR'

export const SET_IS_FETCHING = 'SET_IS_FETCHING'

export const ADD_TODO_LOCAL = 'ADD_TODO_LOCAL'
export const ADD_TODO_SERVER = 'ADD_TODO_SERVER'
export const ADD_TODO_SERVER_ERROR = 'ADD_TODO_SERVER_ERROR'

export const REMOVE_TODO_LOCAL = 'REMOVE_TODO_LOCAL'
export const REMOVE_TODO_SERVER = 'REMOVE_TODO_SERVER'
export const REMOVE_TODO_SERVER_ERROR = 'REMOVE_TODO_SERVER_ERROR'

export const UPDATE_TODO_LOCAL = 'UPDATE_TODO_LOCAL'
export const UPDATE_TODO_SERVER = 'UPDATE_TODO_SERVER'
export const UPDATE_TODO_SERVER_ERROR = 'UPDATE_TODO_SERVER_ERROR'

export const TOGGLE_ALL_TODOS_LOCAL = 'TOGGLE_ALL_LOCAL'
export const TOGGLE_ALL_TODOS_SERVER = 'TOGGLE_ALL_SERVER'
export const TOGGLE_ALL_TODOS_SERVER_ERROR = 'TOGGLE_ALL_TODOS_SERVER_ERROR'

export const CLEAR_COMPLETED_LOCAL = 'CLEAR_COMPLETED_LOCAL'
export const CLEAR_COMPLETED_SERVER = 'CLEAR_COMPLETED_SERVER'
export const CLEAR_COMPLETED_SERVER_ERROR = 'CLEAR_COMPLETED_SERVER_ERROR'

export const TOGGLE_FILTER = 'TOGGLE_FILTER'
